name: Deploy PROD
on:
  workflow_dispatch:
  push:
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Up Environment Variables
      run: |
        cat << 'EOF' > setenv.sh
        #!/bin/bash
        export AUTH_URL="${{ secrets.AUTH_URL }}"
        export SYNC_URL="${{ secrets.SYNC_URL }}"
        export CLIENT_ID="${{ secrets.CLIENT_ID }}"
        export CLIENT_SECRET="${{ secrets.CLIENT_SECRET }}"
        export USERNAME="${{ secrets.USERNAME }}"
        export PASSWORD="${{ secrets.PASSWORD }}"
        export SECURITY_TOKEN="${{ secrets.SECURITY_TOKEN }}"
        EOF
        chmod +x setenv.sh
    
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        WPE_ENV: aiidb
        SCRIPT: setenv.sh
